### ISSUE TITLE
Consider status of ApplicationConfiguration as a subresource in k8s CRD

### ISSUE THREAD

**Issue by 0902horn** [oam-dev/oam-go-sdk#13]
Using /status subresource would introduce following benefits:

> - PUT requests to the /status subresource take a custom resource object and ignore changes to anything except the status stanza.
> - PUT requests to the /status subresource only validate the status stanza of the custom resource.
> - PUT/POST/PATCH requests to the custom resource ignore changes to the status stanza.

BTW, /status subresource has been a [stable feature](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#subresources) since k8s v1.17.

**Comment by hongchaodeng** [comment]
~~What exactly do you want the SDK to do?~~
Understood now:

![91A4AF22-81A0-446D-8053-CC8C8C40A478](https://user-images.githubusercontent.com/920884/72029101-b0441d00-3239-11ea-9cce-916bdae3afc1.png)
