### ISSUE TITLE
Create object-map type for `properties`, `workloadSettings`

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/oam-go-sdk#3]
`properties` are JSON objects usually defined as `map[string]interface{}` in Go.

Currently, they are defined as `[]map[string]intstr.IntOrString`. We should fix the type and also make it work with K8s code-generator.

**Comment by Diddaa** [comment]
lgtw

**Comment by hongchaodeng** [comment]
fixed by https://github.com/oam-dev/oam-go-sdk/pull/6
