### ISSUE TITLE
Use RWMutex instead of Mutex

### ISSUE THREAD

**Issue by dddddai** [oam-dev/oam-go-sdk#45]
https://github.com/oam-dev/oam-go-sdk/blob/202f2890c3aea42e622ae9b612610f4e46496c3e/apis/handlers/status.go#L29-L39
https://github.com/oam-dev/oam-go-sdk/blob/19f328bd6742abb3f16ce7e56d1d0a01c3f8d17a/pkg/oam/types.go#L91-L99

They should use RWMutex instead of Mutex to avoid the contention between readings.

**Comment by dddddai** [comment]
/cc @wonderflow    @hongchaodeng 
If it's necessary,I am willing to contribute : )

**Comment by wonderflow** [comment]
I don't think that's necessary. `oam-go-sdk` focus on `v1alpha1` while we're currently working on `v1alpha2` at [oam-kubernetes-runtime repo](https://github.com/crossplane/oam-kubernetes-runtime). We're glad if you're willing to contribute there.

**Comment by dddddai** [comment]
Thank you,I would close this issue.
